ASURT_2/urls.py
# this file roots the URLconf at the .urls files in each
# app to the URLconf of the project which is in this file

# When somebody requests a page from the website
# Django will load the this
# Python module because it is pointed to by the ROOT_URLCONF setting


from django.conf.urls import url, include
from django.contrib import admin
from ticketSys.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),

    # The include() function allows referencing other URLconfs
    # it chops off whatever part of the URL matched up to that point
    # and sends the remaining string to the included URLconf for further processing.

    # defining the apps URL
    # /tickets/
    url(r'^tickets/', include('ticketSys.urls', namespace='ticketSys', app_name='ticketSys')),

    # /registeration/
    url(r'^registeration/', include('registeration.urls', namespace='registeration', app_name='registeration')),

    # /foreignClubs/
    url(r'^foreignClubs/', include('foreignClubs.urls', namespace='foreignClubs', app_name='foreignClubs')),

    # /events/
    url(r'^events/', include('events.urls', namespace='events', app_name='events')),

    # Default page to access all the work (DEVELOPMENT ONLY)
    url(r'^$', index, name='index'),

]

events/urls.py
from django.conf.urls import url
from . import views

# to namespace this urlpatterns
app_name = 'events'
# make a function that checks whether the user is an authenticated ticket member and call it in every url
urlpatterns = [
    # /events/organizers/
    url(r'^organizers/$', views.organizers, name='organizers'),
]

registeration/urls.py
# this is a simple mapping between URL patterns(simple regular expressions) to
# Python functions(views).
from django.conf.urls import include, url
from . import views

from registeration.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

ticketSys/urls.py
# this is a simple mapping between URL patterns(simple regular expressions) to
# Python functions(views).

from django.conf.urls import url
from . import views

# to namespace this urlpatterns
app_name = 'ticketSys'
# make a function that checks whether the user is an authenticated ticket member and call it in every url
urlpatterns = [
    # /tickets/
    url(r'^$', views.dashBoard, name='dashBoard'),

    # /tickets/add/
    url(r'^add/', views.addTicket, name='add_ticket'),

    # /tickets/123/
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    # /tickets/123/addcomment/
    url(r'^(?P<pk>[0-9]+)/addcomment/$', views.addComment, name='add_comment'),

    # /tickets/123/changestate/
    url(r'^(?P<pk>[0-9]+)/changestate/$', views.changeState, name='change_state'),

    # /tickets/login/
    url(r'^login/', views.login, name='login'),
    # /chooseRTMember//
    url(r'^chooseRTMember/', views.chooseRTMember, name='choose_RTMember'),
    # /RTMemberAdded/
    url(r'^RTMemberAdded/$', views.addRTMember, name='RTMember_Added'),

]

registeration/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

# Create your models here.

registeration/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password= forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User 
		fields = ['username', 'email', 'password']

registeration/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import UserForm
from ticketSys.models import Ticket
from ticketSys.views import dashBoard
# Create your views here.
# def registeration(request):
# 	x = HttpResponse("<h1>hi</h1>")
# 	return x


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'registeration/login.html')
    else:
    	return render(request, 'registeration/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'registeration/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # Tickets = Ticket.objects.all()
                # context={'Tickets':Tickets,}
                # return render(request, 'ticketSys/dashBoard.html', context )
                # return render(request, 'registeration/index.html',)
                return dashBoard(request)
            else:
                return render(request, 'registeration/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'registeration/login.html', {'error_message': 'Invalid login'})
    return render(request, 'registeration/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'registeration/index.html')
    context = {
        "form": form,
    }
    return render(request, 'registeration/register.html', context)

registeration/templates/registeration/base.html
<!--DOCTYPE html-->
    {% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}ASURT{% endblock %}</title><!--
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
-->
<!-- Latest compiled and minified JavaScript -->
  	<link href="{% static 'registeration/css/bootstrap.css' %}" type="text/css" rel="stylesheet">

  	<link href="{% static 'registeration/css/style_footer.css' %}" type="text/css" rel="stylesheet">
  	<link href="{% static 'registeration/css/style_header.css' %}" type="text/css" rel="stylesheet">
  	<link href="{% static 'registeration/css/style.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-default header nav1" style="width:">
  <div class="container-fluid">
    <div class="navbar-header">
    <img class="img-responsive logo ic2" src="{% static 'registeration/images/logo.png' %}">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="row">
    <div class="collapse navbar-collapse  nav1 " id="myNavbar">
    <div class="ic">
    <a class="navbar-brand " href="#"><img class="img-responsive logo " src="{% static 'registeration/images/logo.png' %}" alt=""></a>
    </div>
    <div>
     <ul class="nav navbar-nav">
        <li><a href="http://asuracingteam.org/about">ABOUT US</a></li>
        <li><a  href="http://asuracingteam.org/achievements">ACHIEVEMENTS</a></li>
        <li class="navbar-dropdown-toggle">
          <!--<a  href="">OUR PROJECTS</a></li>-->
        <!--&lt;!&ndash; <li ng-if="root.me"><a ng-class="{active: vm.isActive('/apply')}" ng-href="/apply">APPLY</a></li> &ndash;&gt;-->
        <!--<li ng-if="!root.me" class="navbar-dropdown-toggle">-->
          <!--<a  href="">JOIN US</a></li>-->
        <li ng-if="root.me"><a  href="http://asuracingteam.org/profile">PROFILE</a></li>
        <!-- <li ng-if="!root.me"><a ng-class="{active: vm.isActive('/user/login')}" href="/user/login">LOGIN</a></li> -->
        <li><a  href="http://asuracingteam.org/gallery">GALLERY</a></li>
        <li><a  href="http://asuracingteam.org/contact">CONTACT US</a></li>
        <li><a  href="{% url 'ticketSys:dashBoard'  %}">TICKET SYSTEM</a></li>
         <li ng-if="root.me"><a ng-click="vm.logout()" href="{% url 'registeration:logout_user' %}">LOGOUT</a></li>

      </ul>
      </div>
    </div>
    </div>
  </div>
</nav>
<div> <!-- header image -->
  <img src="{% static 'registeration/images/Headers/formula.jpg' %}" class="header_image">
</div>
  <div class="col-md-offset-10">
  <ul class="ulist">
    <li><a href="https://www.linkedin.com/in/asu-racing-team-00786111a" target="_blank"><img src="{% static 'registeration/images/Icon/2.jpg' %}" class="social-links" /></a></li>
    <li><a href="https://youtube.com/user/asuracingteam" target="_blank"><img src="{% static 'registeration/images/Icon/1.jpg' %}" class="social-links"  /></a></li>
    <li><a href="https://instagram.com/asurt.live/" target="_blank"><img src="{% static 'registeration/images/Icon/3.jpg' %}" class="social-links" /></a></li>
    <li><a href="https://twitter.com/asuracingteam" target="_blank"><img src="{% static 'registeration/images/Icon/4.jpg' %}" class="social-links" /></a></li>
    <li><a href="https://facebook.com/ASU.Racing.Team" target="_blank"><img src="{% static 'registeration/images/Icon/5.jpg' %}" class="social-links" /></a></li>
    </ul>
  </div>
<!------------------------------------------------------------------------->

    <div class="container rtPanel">
	 {% block body %}
	 {% endblock %}
    </div>
</div>
</div>
<div class="container-body" style="margin-top:3%">
      <div class="container-section">
        <h4 class="text-left" style="margin-left:12%"><strong>SPONSORS</strong></h4>
        <img class="img-responsive" style="margin: 0 auto;" src="{% static 'registeration/images/sponsors.jpg' %}" />
      </div>
    </div>

    <!--<div class="footer footer1">-->
      <div class="footer footer1">
          <div class="row"style="margin-right:10px; margin-bottom:-20px;">
            <div class="col-sm-5 col-xs-12"style=" padding-bottom:10px;">
              <img class="img-responsive img1" src="{% static 'registeration/images/black.jpg' %}" />
              <br>
              <div class="img1" style="font-size:11px">
                Copyright &copy; 2016 ASU RACING TEAM <br> All Rights Reserved.
              </div>
            </div>
            <div class="col-sm-7 col-xs-11  text-right footer1 forh" style="padding-top:20px;" >
            <ul class="ulm">
            	<li><a href="http://asuracingteam.org/about" class="lie"> ABOUT US </li>
            	<li><a href="http://asuracingteam.org/achievements" class="lie" style="padding-right:5px"> ACHIEVEMENTS </li>
            	<li><a href="" style="color:white"> OUR PROJECTS <br>
            	<ul class="uls">
            		<li><a href="http://asuracingteam.org/teams/formula" style="color:white"> FORMULA STUDENT TEAM</li>
            		<li><a href="http://asuracingteam.org/teams/eco" style="color:white"> ECO GASOLINE TEAM</li>
            		<li><a href="http://asuracingteam.org/teams/hybrid" style="color:white"> HYBRID ELECTRIC TEAM </li>
            		<li><a href="http://asuracingteam.org/teams/rov" style="color:white"> ROV TEAM </li>

            	</ul>
            	</li>
            	<li><a href="http://asuracingteam.org/user/login" class="lie"> LOGIN </li>
            	<li><a href="http://asuracingteam.org/gallery" class="lie"> GALLERY </li>
            	<li><a href="http://asuracingteam.org/contact" class="lie"> CONTACT US </li>
            </ul>

            </div>
          </div>
      </div>
    <!--</div>-->

<!-- JS files-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'registeration/js/bootstrap.js' %}" />

</body>
</html>

registeration/templates/registeration/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10" >
			<span class="text-danger small">{{ field.error }}</span>						
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

registeration/templates/registeration/index.html
{% extends 'registeration/base.html' %}
	
{% block body %}<div class="container">
                    {% csrf_token %}
		<h1 class="logged-panel">Welcome {{ user }}</h1></div>
{% endblock %}

registeration/templates/registeration/login.html
{% extends 'registeration/base.html' %}
{% block title %}Log In{% endblock %}


{% block body %}
<div class="container-fluid"style="margin-left:27%">

    <div class="row">
        <div class="col-xs-12 col-md-7">
            <div class="panel panel-default login-panel">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p class="error"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'registeration:login_user' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'registeration:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

registeration/templates/registeration/reg_form.html
{% extends 'registeration/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid Reg-panel">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'registeration/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>

</div>

{% endblock %}

registeration/templates/registeration/register.html
{% extends 'registeration/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid Reg-panel">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'registeration/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'registeration:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}