ASURT_2/urls.py
# this file roots the URLconf at the .urls files in each
# app to the URLconf of the project which is in this file

# When somebody requests a page from the website
# Django will load the this
# Python module because it is pointed to by the ROOT_URLCONF setting


from django.conf.urls import url, include
from django.contrib import admin
from ticketSys.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),

    # The include() function allows referencing other URLconfs
    # it chops off whatever part of the URL matched up to that point
    # and sends the remaining string to the included URLconf for further processing.

    # defining the apps URL
    # /tickets/
    url(r'^tickets/', include('ticketSys.urls', namespace='ticketSys', app_name='ticketSys')),

    # /registeration/
    url(r'^registeration/', include('registeration.urls', namespace='registeration', app_name='registeration')),

    # /foreignClubs/
    url(r'^foreignClubs/', include('foreignClubs.urls', namespace='foreignClubs', app_name='foreignClubs')),

    # /events/
    url(r'^events/', include('events.urls', namespace='events', app_name='events')),

    # Default page to access all the work (DEVELOPMENT ONLY)
    url(r'^$', index, name='index'),

]

events/urls.py
from django.conf.urls import url
from . import views

# to namespace this urlpatterns
app_name = 'events'
# make a function that checks whether the user is an authenticated ticket member and call it in every url
urlpatterns = [
    # /events/organizers/
    url(r'^organizers/$', views.organizers, name='organizers'),
]

foreignClubs/urls.py
from django.conf.urls import url
from . import views

# to namespace this urlpatterns
app_name = 'foreignClubs'
# make a function that checks whether the user is an authenticated ticket member and call it in every url
urlpatterns = [
    # /foreignClubs/heads/
    url(r'^heads/$', views.heads, name='heads'),
]

registeration/urls.py
# this is a simple mapping between URL patterns(simple regular expressions) to
# Python functions(views).
from django.conf.urls import include, url
from . import views

from registeration.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

ticketSys/urls.py
# this is a simple mapping between URL patterns(simple regular expressions) to
# Python functions(views).

from django.conf.urls import url
from . import views

# to namespace this urlpatterns
app_name = 'ticketSys'
# make a function that checks whether the user is an authenticated ticket member and call it in every url
urlpatterns = [
    # /tickets/
    url(r'^$', views.dashBoard, name='dashBoard'),

    # /tickets/add/
    url(r'^add/', views.addTicket, name='add_ticket'),

    # /tickets/123/
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    # /tickets/123/addcomment/
    url(r'^(?P<pk>[0-9]+)/addcomment/$', views.addComment, name='add_comment'),

    # /tickets/123/changestate/
    url(r'^(?P<pk>[0-9]+)/changestate/$', views.changeState, name='change_state'),

    # /tickets/login/
    url(r'^login/', views.login, name='login'),
    # /chooseRTMember//
    url(r'^chooseRTMember/', views.chooseRTMember, name='choose_RTMember'),
    # /RTMemberAdded/
    url(r'^RTMemberAdded/$', views.addRTMember, name='RTMember_Added'),

]

ticketSys/models.py
# Each model is represented by a class that subclasses django.db.models.Model.
# Each model has a number of class variables,
# each of which represents a database field in the model.
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User  # should be changed to the proper way for integrations
from rtMembers.models import RTMember
from django.forms import forms
from django.forms import ImageField


# For  holding all States

class States:
    STATES = (
        (0, 'WAITING_HR'), (1, 'WAITING_IT'), (2, 'WAITING'), (3, 'SOLVED')
    )


class TicketMember(models.Model):  # table for RTMembers inrolled in the ticketSystem
    rtMember = models.OneToOneField(to=RTMember, related_name='ticketMember')  # the member from RTMembers

    def __str__(self):
        return self.rtMember.__str__()


# Each field is represented by an instance of a Field class
# CharField for character fields

# Relationship is defined, using ForeignKey. that tells django for example each
# Ticket instance created from this class will be related to a single RTmember.
class Ticket(models.Model):
    ticketMember = models.ForeignKey(TicketMember, on_delete=models.CASCADE,related_name='ticket')  # RTmember who issued the ticket
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # the user who the ticket is about
    state = models.IntegerField(choices=States.STATES)  # the current state of the ticket
    title = models.CharField(max_length=1000)  # the title
    content = models.CharField(max_length=1000)  # the content

    # defines a URL, used in the admin area, for each record.
    def get_absolute_url(self):
        return reverse('ticketSys:detail', kwargs={'pk': self.pk})

    # to return data as a string
    def __str__(self):
        return self.title + ' - ' + States.STATES[self.state][1]


class TicketComment(models.Model):
    ticketMember = models.ForeignKey(TicketMember, on_delete=models.CASCADE,
                                     related_name='comment')  # RTmember submitted the comment
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)  # Related ticket
    comment = models.CharField(max_length=1000)  # The content of the comment


class CommentImg(models.Model):
    comment = models.ForeignKey(TicketComment, on_delete=models.CASCADE, related_name='img')  # Related comment's image
    url = models.CharField(max_length=1000)  # URL of the image


class TicketImg(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='img')  # Related ticket's image
    url = models.CharField(max_length=1000)  # URL of the image


    # class CommentImg(models.Model):
    # 	image = FileField(upload_to=None[, max_length=100, **options]

ticketSys/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from rtMembers.models import RTMember, Roles
from ticketSys.models import TicketMember, TicketComment, Ticket, States
from django.contrib.auth.models import User
from django.db.models import Q
from ticketSys import emailSender
from django.contrib.auth import authenticate, login
from django.core.files.base import ContentFile


# detail get called like this
# detail(request=<HttpRequest object>, question_id='34')
# question_id='34' from (?P<pk>[0-9]+)/ part of the URL

def isAuthTicketMember(request):
    if request.user.is_authenticated():
        if isTicketMember(request.user):
            return True
    return False


def isTicketMember(user):
    try:
        if getTicketMemberFromUser(user) is not None:
            return True
    except:
        return False
    return False


# it gets all the details about a specified ticket and render it to the template
def detail(request, pk):
    if not isAuthTicketMember(request):  # continue if only the user is a TicketMember
        return redirect('registeration:index')
    # Get the ticket related with the pk from the database or rise an 404 error if it is not found
    ticket = get_object_or_404(Ticket, pk=pk)
    # Get the comments related to the Ticket to be displayed in the details template
    comms = TicketComment.objects.filter(ticket_id=pk)
    # States.STATES is to get the tuble in class States that holds all the possible states
    context = {'ticket': ticket, 'comments': comms, 'states': States.STATES}
    return render(request, 'ticketSys/detail.html', context)  # Send to the template


def addComment(request, pk):  # add comment to the ticket detail page
    if not isAuthTicketMember(request):  # continue if only the user is a TicketMember
        return redirect('registeration:index')
    comment = request.POST['comment']
    user = request.user
    tm = getTicketMemberFromUser(user)
    ticket = Ticket.objects.get(id=pk)
    comm = TicketComment(ticketMember=tm, ticket=ticket, comment=comment)
    comm.save()
    return render(request, 'ticketSys/comment.html', {'com': comm})


def changeState(request, pk):
    if not isAuthTicketMember(request):  # continue if only the user is a TicketMember
        return redirect('registeration:index')
    s = request.POST['state']
    t = Ticket.objects.get(id=pk)
    # check if the member able to change the state of the ticket
    # if state was  'waiting_it'
    # the IT members or All heads only can be able to change the state
    # NOTE any Managerial head begin with X
    # (0, 'WAITING_HR'), (1, 'WAITING_IT'), (2, 'WAITING'), (3, 'SOLVED')
    if t.state is not s:
        domain = request.META['HTTP_HOST']
        emailRelatedMembers(s, pk, domain)  # to notify who should be notified by email or whatever
        t.state = s
        t.save()

    return redirect('ticketSys:detail', pk)


#  login form
#  data about the ticket in the mail
#  add image
#  don't show RTMembers in the user list
#  can search for the user
#  change to function and fix error
def addTicket(request):
    if not isAuthTicketMember(request):  # continue if only the user is a TicketMember
        return redirect('registeration:index')

    if request.method == "GET":  # the user is entering the addTicket page, just view the page
        users = User.objects.filter(rtMember=None)  # get all users that are not RTMembers
        context = {'users': users}
        return render(request, 'ticketSys/addTicket.html', context)

    else:  # the user has submitted the form, validate the data
        try:
            ticketMember = getTicketMemberFromUser(request.user)
            userid = request.POST['selectedUser']
            user = User.objects.get(id=userid)
            try:  # fetch the state of the ticket
                request.POST['needhr']
                # Need HR approval
                state = 0
            except:  # Does not need HR approval
                state = 1

            title = request.POST['title']
            content = request.POST['content']
            if len(title) < 2 or len(content) < 2:  # validate that the title and content are not empty

                return redirect('ticketSys:add_ticket')

            ticket = Ticket(ticketMember=ticketMember, user=user, state=state, title=title, content=content)
            ticket.save()
            domain = request.META['HTTP_HOST']
            try:  # send emails to the concerned ticketMembers
                if state == 0:
                    emailHR(ticket.id, domain)
                else:
                    emailIT(ticket.id, domain)
            except:
                print('Error while emailing')

        except:
            redirect('ticketSys:add_ticket')

    return redirect('ticketSys:dashBoard')


# send emails to the RTMembers with role HR
def emailHR(pk, domain):
    rtMembers = RTMember.objects.filter(
        Q(role=2) | Q(role=3) | Q(role=4) | Q(role=5))  # the indices of the HR(OD,REC) in ROLES
    for rtMember in rtMembers:
        if isTicketMember(rtMember.user):
            receiver = getUserFromRTMember(rtMember)
            if receiver.email is not '' and receiver.email is not None and receiver.email != '':
                emailSender.autoMailSender(receiver.email, pk, domain)


# send emails to the RTMembers with role IT
def emailIT(pk, domain):
    rtMembers = RTMember.objects.filter(Q(role=0) | Q(role=1))  # the indices of the IT in ROLES
    for rtMember in rtMembers:
        if isTicketMember(rtMember.user):
            receiver = getUserFromRTMember(rtMember)
            if receiver.email is not '' and receiver.email is not None and receiver.email != '':  # this lets empty emails get to the function solve that
                emailSender.autoMailSender(receiver.email, pk, domain)


# email the member associated with the change depending on his/her role
def emailRelatedMembers(state, pk, domain):
    # (0, 'WAITING_HR'), (1, 'WAITING_IT'), (2, 'WAITING'), (3, 'SOLVED')
    if state == '0':  # handling state 0 -> HR
        emailHR(pk, domain)

    elif state == '1':  # handling state 1 -> IT
        emailIT(pk, domain)

    elif state == '2':  # send email to the ticket starter
        ticket = Ticket.objects.get(id=pk)
        ticketmember = TicketMember.objects.get(id=ticket.ticketMember_id)
        rtMember = RTMember.objects.get(id=ticketmember.rtMember_id)
        receiver = getUserFromRTMember(rtMember)
        if receiver.email is not '' and receiver.email is not None and receiver.email != '':
            emailSender.autoMailSender(receiver.email, pk, domain)


def dashBoard(request):
    if not isAuthTicketMember(request):  # continue if only the user is a TicketMember
        return redirect('registeration:index')
    tickets = Ticket.objects.all()  # get all the tickets in the database
    context = {'tickets': tickets}
    return render(request, 'ticketSys/dashboard.html', context)  # send it to the template


# returns the TicketMember associated with that User
def getTicketMemberFromUser(user):
    rtmember = RTMember.objects.get(user=user)
    return TicketMember.objects.get(rtMember=rtmember)


# returns the User associated with that RTMember
def getUserFromRTMember(rtMember):
    memberID = rtMember.user.id
    return User.objects.get(id=memberID)


# returns the RTMember related to the user
def getRTMemberFromUser(request):
    user = request.user
    rtMember = RTMember.objects.get(user=user.id)
    return rtMember


#  use this function to enble and disable a button in the system
def isRTMemberHead(rtMember):
    if rtMember.role == 1 or rtMember.role == 3 or rtMember.role == 5 or rtMember.role == 7 or rtMember.role == 9:
        return True

    return False


# related to Comment Images

#
# def save_file(request):
# 	mymodel = CommentImg.objects.get(id=1)
# 	file_content = ContentFile(request.FILES['video'].read())
# 	mymodel.video.save(request.FILES['video'].name, file_content)


def chooseRTMember(request):
    rtMember = getRTMemberFromUser(request)
    if isRTMemberHead(rtMember):
        context = {'users': User.objects.all(), 'roles': Roles.ROLES}
        return render(request, 'ticketSys/addRTMember.html', context)
    else:
        return redirect('registeration:index')


def addRTMember(request):
    user = request.POST['user']
    roleOfRTMember = request.POST['role']
    normalUser = User.objects.get(id=user)
    rtMember = RTMember(user=normalUser, role=roleOfRTMember)
    rtMember.save()
    return redirect('ticketSys:choose_RTMember')


def index(request):  # Used for DEVELOPMENTAL use only to make our lives easier shows shortcuts at the 1st page
    return render(request, 'ticketSys/index.html')

ticketSys/templates/ticketSys/addRTMember.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add RTMember</title>
</head>
<body>
<form action="{% url 'ticketSys:RTMember_Added'%}" method="post">
{% csrf_token %}
<select name="user">
<option>-- select an option -- </option>
        {% for user in users %}
            <option value="{{ user.id }}"
                    >{{ user }}</option>

        {% endfor %}
    </select>
 <span>Users</span>
<select name="role">
<option>-- select an option -- </option>
        {% for role in roles%}
            <option value="{{ role.0 }}"
                    >{{ role.1 }}</option>

        {% endfor %}
    </select>
<span>Roles</span>
        <button type="submit" class="btn btn-primary">Add RTMember</button>
</form>
</body>
</html>

ticketSys/templates/ticketSys/addTicket.html
{% extends 'ticketSys/base.html' %}
    {% load staticfiles %}

{% block title %}Add Ticket{% endblock %}


{% block body %}
<h2>Hello, {{ user }}</h2>
<a href="{% url 'ticketSys:dashBoard'  %}"><button class="btn btn-primary">Back To Dashboard</button></a>
 {% if error_message %}
                <div class="alert alert-danger" role="alert">Error Wrong Entry !!!</div>

        {% endif %}
<div class="container">
        <div class="panel panel-default ticket-panel">
          <div class="panel-body">
            <form action="{% url 'ticketSys:add_ticket' %}" method="post">
                {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Title</label>
                <input class="form-control" type="text" name="title" placeholder="Enter the ticket title here..." required="true"></input>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Select User </label>
                        <select name="selectedUser">
                        {% for user in users %}
                            <option value="{{ user.id }}">{{ user }}</option>
                        {% endfor %}
                        </select>
              </div>
                <div class="form-group">
                     <label>Need HR ?</label> <input type="checkbox" name="needhr" id="needhr" value="yes"/><br>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Content</label>
                    <input type="text" class="form-control" id="content" placeholder="Enter the content..." name="content" required="true">
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div></div></div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/main.js"></script>

{% endblock %}

ticketSys/templates/ticketSys/comment.html
{% load staticfiles %}

<comment>
    <div class="comments">

        <!-- start comment block -->
        <div class="comment">
            <p><strong>{{ com.memberid }}</strong></p>
            <a class="comment-avatar pull-left" href="#"><img
                    src="{% static 'ticketSys/images/pp.jpg' %}"></a>

            <div class="comment-text">
                <p>{{ com.comment }}</p>
            </div>
        </div>
        <div class="clearfix"></div>
        <!-- end comment block-->
    </div>

    <div class="clearfix"></div>
</comment>

ticketSys/templates/ticketSys/dashboard.html
{% extends 'ticketSys/base.html' %}
    {% load staticfiles %}

{% block title %}Tickets Dashboard{% endblock %}

{% block head %}
  	<link href="{% static 'ticketSys/css/Dashboard_Style.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block body %}
<!--<h1>Tickets Dashboard</h1>-->
<!--<h2>Hello, {{ user }}!</h2>-->
<!--<h4><a href="{% url 'ticketSys:add_ticket' %}">Add Ticket</a></h4>-->
<!--<span><a href="/admin/">admin</a></span>-->
<!--<span><a href="{% url 'registeration:login_user' %}">login_user</a></span>-->
<!--<span><a href="{% url 'registeration:logout_user' %}">logout_user</a></span>-->
<!--<span><a href="{% url 'registeration:register' %}">registeration</a></span>-->
<!--<h3>Total {{ tickets.count }} Tickets :</h3>-->

<!--<ul>-->
    <!--{% for ticket in tickets %} &lt;!&ndash;todo display the state in a string&ndash;&gt;-->
        <!--<li><a href="{% url 'ticketSys:detail' ticket.id %}">{{ ticket.title }} - {{ ticket.state }}</a></li>-->
    <!--{% endfor %}-->
<!--</ul>-->


<!-- &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&-->


<div class="container">
	<div class="row">

		<section class="content">
			<h1>Tickets Dashboard</h1>
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="pull-right">
							<div class="btn-group">
								<a href="{% url 'ticketSys:add_ticket' %}"><button type="button" class="btn btn-success btn-filter">Add Ticket</button></a>
								<br>
								<br>
                                <!--<button type="button" class="btn btn-warning btn-filter" data-target="pendiente">Pendiente</button>-->
								<!--<button type="button" class="btn btn-danger btn-filter" data-target="cancelado">Cancelado</button>-->
								<!--<button type="button" class="btn btn-default btn-filter" data-target="all">Todos</button>-->
							</div>
						</div>
						<div class="table-container">
							<table class="table table-filter">
								<tbody>
																	<div class="container">

                                {% for ticket in tickets reversed %}
									<div class="row">
									<tr>
										<td>
											<div class="media">
                                                <a class="comment-avatar pull-left" href="{% url 'ticketSys:detail' ticket.id %}"><img src="{% static 'ticketSys/images/pp.jpg' %}"></a>
                                                <div class="media-body">
													<h4 class="title">
                                                        <a href="{% url 'ticketSys:detail' ticket.id %}">{{ ticket.ticketMember }}: {{ ticket.title }}</a>
                                                        <span class="pull-right pagado state"><strong>{{ ticket.get_state_display }}</strong></span>
													</h4>
													<!--<textarea class="form-control" readonly rows="2">{{ ticket.content }}</textarea>-->
												</div>
											</div>
										</td>
									</tr></div>
                                    {% endfor %}
							</tbody>
							</table>
						</div>
					</div>
				</div>

			</div>
		</section>

	</div>
</div>


<script src="{% static 'ticketSys/js/Dashboard_Script.js' %}"></script>

{% endblock %}

ticketSys/templates/ticketSys/detail.html
{% extends 'ticketSys/base.html' %}
{% load staticfiles %}

{% block title %}Ticket Detail{% endblock %}


{% block body %}
    <div class="container ticketView-panel">
        <!--on clicking go to the URL with the name dashBoard in the app ticketSys-->
        <a href="{% url 'ticketSys:dashBoard' %}">
            <button class="btn btn-primary">Back To Dashboard</button>
        </a>
        <!--<span><a href="{% url 'ticketSys:dashBoard'  %}"><&#45;&#45;Back</a></span>-->
        <h3> Hello, {{ user }}!</h3>


        <section>
            <div class="container">
                <div class="panel panel-default ticket-panel">
                    <div class="panel-body">
                        <form action="{% url 'ticketSys:change_state' ticket.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="exampleInputEmail1">Title</label>
                                <text class="form-control" type="text" readonly>{{ ticket.title }}</text>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">User </label>
                                <text class="form-control" type="text" disabled>{{ ticket.userid }}</text>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Submitted By </label>
                                <text class="form-control" type="text" disabled>{{ ticket.memberid }}</text>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Content</label>
                                <textarea class="form-control" rows="3" readonly>{{ ticket.content }}</textarea>
                            </div>
                            <!--<div class="checkbox">-->
                            <!--<label>-->
                            <!--<input type="checkbox"> HR Approval-->
                            <!--</label><br>-->
                            <!--<label>-->
                            <!--<input type="checkbox"> Solved-->
                            <!--</label><br>-->
                            <!--<label>-->
                            <!--<input type="checkbox"> Closed-->
                            <!--</label>-->
                            <!--</div>-->
                            <strong>Current State :</strong>

                            <select name="state">
                                {% for state in states %}
                                    <option value="{{ state.0 }}"  {% if state.0 == ticket.state %}
                                            selected style="color: orangered"{% endif %}>{{ state.1 }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-primary">Change State</button>
                        </form>
                    </div>
                </div>
            </div><!-- end panal container-->
        </section>
        <div class='container comments'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Comments</h3>
                </div>
                <!--  form  -->
                <form id="add_comment_form" action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" id="comment" placeholder="Your comment here"
                               name="comment">
                    </div>
                    <button type="submit" class="btn btn-primary">comment</button>
                </form>
                <!-- </form> -->
                <!-- Comments content -->
                <div class="panel-body">
                    <!-- comment block-->
                    <div id="comments">
                        {% for com in comments reversed %}
                            {% include 'ticketSys/comment.html' %}
                        {% endfor %}
                    </div>
                </div>
                <!-- Comments content -->

            </div>
            <!-- end write a comment section -->

        </div>
    </div>
    </div><!-- end comments panel-->
    </div>
    <!--<div class='container '>-->
    <!--<div class="ticket-actions">-->
    <!--<button type="submit" class="btn btn-primary">Change HR State</button>-->
    <!--<button type="button" class="btn btn-warning">Save</button>-->
    <!--<button type="button" class="btn btn-success">Mark as Solved</button>-->
    <!--<button type="button" class="btn btn-danger">Mark as Closed</button>-->
    <!--</div>&lt;!&ndash; end ticket-actions &ndash;&gt;-->
    <!--</div>-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/main.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript">
        /*Add comment and don't refresh Function */
        $(function () {
            $('#add_comment_form').on('submit', function (e) {
                e.preventDefault();
                $.ajax({
                    type: 'post',
                    url: '{% url 'ticketSys:add_comment' ticket.id %}',
                    data: $('#add_comment_form').serialize(),
                    success: function (data) {
                        $('#add_comment_form')[0].reset();
                        document.getElementById("comments").innerHTML = data + document.getElementById("comments").innerHTML;
                        $('html, body').animate({
                            scrollTop: $("#comments").offset().top -200
                        }, 1000);
                    }
                });
            });
        });
        /* Add comment and don't refresh Function  */
    </script>

{% endblock %}

ticketSys/templates/ticketSys/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ticketSys/templates/ticketSys/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ASURacingTeam DEV portal</title>
</head>
<body>
<a href="{% url 'ticketSys:dashBoard' %}">dashBoard</a><br>
<a href="{% url 'foreignClubs:heads' %}">heads</a><br>
<a href="{% url 'events:organizers' %}">organizers</a><br>
<a href="admin/">admin</a><br>
</body>
</html>

ticketSys/templates/ticketSys/login.html
{% extends 'registeration/base.html' %}
{% block title %}Log In{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default login-panel">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'registeration:login_user' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'registeration:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}